
version: '3.8'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: employee-attendance-api
    ports:
      - '${APP_PORT:-8000}:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: employee_attendance
      DB_USERNAME: sail
      DB_PASSWORD: password
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'employee_attendance'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sail-mysql:/var/lib/mysql'

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  sail-mysql:
    driver: local

